# Generated by Django 5.2.7 on 2025-10-01 20:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('social_accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('design_url', models.URLField(blank=True, help_text='URL to Canva design or uploaded image')),
                ('design_thumbnail', models.URLField(blank=True)),
                ('ai_generated', models.BooleanField(default=False)),
                ('ai_prompt', models.TextField(blank=True, help_text='Original AI prompt used')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('brand_voice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='accounts.brandvoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostPlatform',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform_content', models.TextField(blank=True, help_text='Platform-optimized content')),
                ('platform_specific_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('platform_post_id', models.CharField(blank=True, help_text='ID from social platform', max_length=200)),
                ('platform_post_url', models.URLField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('last_retry_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_accounts.socialaccount')),
            ],
            options={
                'verbose_name': 'Post Platform',
                'verbose_name_plural': 'Post Platforms',
                'db_table': 'post_platforms',
                'unique_together': {('post', 'social_account')},
            },
        ),
        migrations.AddField(
            model_name='post',
            name='platforms',
            field=models.ManyToManyField(related_name='posts', through='posts.PostPlatform', to='social_accounts.socialaccount'),
        ),
        migrations.CreateModel(
            name='ContentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('announcement', 'Announcement'), ('educational', 'Educational'), ('promotional', 'Promotional'), ('engagement', 'Engagement'), ('news', 'News'), ('personal', 'Personal')], max_length=20)),
                ('template_content', models.TextField(help_text='Use {variables} for dynamic content')),
                ('description', models.TextField(blank=True)),
                ('variables', models.JSONField(default=list, help_text='List of variable names used in template')),
                ('usage_count', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Template',
                'verbose_name_plural': 'Content Templates',
                'db_table': 'content_templates',
                'unique_together': {('user', 'name')},
            },
        ),
    ]
