# Generated by Django 5.2.7 on 2025-10-07 21:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='canva_design_id',
            field=models.CharField(blank=True, help_text='Canva design ID', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='custom_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, help_text='Post description/summary'),
        ),
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.JSONField(default=list, help_text='List of hashtags'),
        ),
        migrations.AddField(
            model_name='post',
            name='requires_approval',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='AIGeneratedContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_info', models.JSONField(help_text='Company information used for generation')),
                ('generation_prompt', models.TextField(help_text='AI prompt used for generation')),
                ('language', models.CharField(default='az', max_length=10)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='generating', max_length=20)),
                ('total_posts', models.IntegerField(default=10)),
                ('approved_posts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_content_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Generated Content',
                'verbose_name_plural': 'AI Generated Content',
                'db_table': 'ai_generated_content',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='ai_content_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.aigeneratedcontent'),
        ),
    ]
