# Generated by Django 5.2.4 on 2025-10-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_approved_at_post_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='design_specs',
            field=models.JSONField(blank=True, help_text='AI-generated design specifications', null=True),
        ),
    ]
