# Generated by Django 5.2.4 on 2025-10-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_design_specs'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imgly_scene',
            field=models.JSONField(blank=True, help_text='img.ly editor scene state for re-editing', null=True),
        ),
    ]
