# Generated by Django 5.2.3 on 2025-12-11 06:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_imgly_scene'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, help_text='Supabase Storage URL for the image'),
        ),
        migrations.CreateModel(
            name='PostPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('saves', models.IntegerField(default=0, help_text='Instagram saves, LinkedIn saves, etc.')),
                ('reach', models.IntegerField(default=0, help_text='Unique users who saw the post')),
                ('impressions', models.IntegerField(default=0, help_text='Total number of times post was shown')),
                ('engagement_rate', models.DecimalField(blank=True, decimal_places=2, help_text='(likes + comments + shares) / reach * 100', max_digits=5, null=True)),
                ('video_views', models.IntegerField(default=0)),
                ('video_completion_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('link_clicks', models.IntegerField(default=0)),
                ('additional_metrics', models.JSONField(blank=True, default=dict, help_text='Platform-specific metrics (e.g., profile visits, website clicks)')),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='posts.postplatform')),
            ],
            options={
                'verbose_name': 'Post Performance',
                'verbose_name_plural': 'Post Performances',
                'db_table': 'post_performance',
                'ordering': ['-updated_at'],
                'unique_together': {('post_platform',)},
            },
        ),
    ]
