# Generated by Django 5.2.4 on 2025-10-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='profile_picture_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
