# Generated by Django 5.2.3 on 2025-12-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_accounts', '0002_alter_socialaccount_profile_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='platform',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('telegram', 'Telegram'), ('instagram', 'Instagram'), ('twitter', 'Twitter/X'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('tiktok', 'TikTok')], max_length=20),
        ),
    ]
