# Generated by Django 5.2.3 on 2026-01-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_accounts', '0003_alter_socialaccount_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='profile_picture_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
