# Generated by Django 5.0.10 on 2026-02-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_accounts', '0004_increase_profile_picture_url_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='profile_picture_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
