# Generated by Django 5.2.7 on 2025-12-05 08:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaAdSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ad_set_id', models.CharField(help_text='Meta Ad Set ID', max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('DELETED', 'Deleted'), ('ARCHIVED', 'Archived')], default='PAUSED', max_length=20)),
                ('daily_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('lifetime_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('billing_event', models.CharField(blank=True, help_text='IMPRESSIONS, CLICKS, etc.', max_length=50)),
                ('optimization_goal', models.CharField(blank=True, help_text='REACH, CLICKS, etc.', max_length=50)),
                ('targeting', models.JSONField(blank=True, default=dict, help_text='Targeting criteria')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meta Ad Set',
                'verbose_name_plural': 'Meta Ad Sets',
                'db_table': 'meta_ad_sets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetaAdAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_id', models.CharField(help_text='Meta Ad Account ID', max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('access_token_encrypted', models.TextField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISABLED', 'Disabled'), ('UNSETTLED', 'Unsettled'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_ad_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta Ad Account',
                'verbose_name_plural': 'Meta Ad Accounts',
                'db_table': 'meta_ad_accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetaAd',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ad_id', models.CharField(help_text='Meta Ad ID', max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('DELETED', 'Deleted'), ('ARCHIVED', 'Archived')], default='PAUSED', max_length=20)),
                ('creative', models.JSONField(blank=True, default=dict, help_text='Ad creative data')),
                ('meta_created_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ad_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='meta_ads.metaadset')),
            ],
            options={
                'verbose_name': 'Meta Ad',
                'verbose_name_plural': 'Meta Ads',
                'db_table': 'meta_ads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetaCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campaign_id', models.CharField(help_text='Meta Campaign ID', max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('DELETED', 'Deleted'), ('ARCHIVED', 'Archived')], default='PAUSED', max_length=20)),
                ('objective', models.CharField(help_text='Campaign objective', max_length=50)),
                ('daily_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('lifetime_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('meta_created_time', models.DateTimeField(blank=True, help_text='Created time from Meta', null=True)),
                ('meta_updated_time', models.DateTimeField(blank=True, help_text='Updated time from Meta', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='meta_ads.metaadaccount')),
            ],
            options={
                'verbose_name': 'Meta Campaign',
                'verbose_name_plural': 'Meta Campaigns',
                'db_table': 'meta_campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='metaadset',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_sets', to='meta_ads.metacampaign'),
        ),
        migrations.CreateModel(
            name='MetaInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_start', models.DateField()),
                ('date_stop', models.DateField()),
                ('impressions', models.BigIntegerField(default=0)),
                ('reach', models.BigIntegerField(default=0)),
                ('clicks', models.BigIntegerField(default=0)),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cpm', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per 1000 impressions', max_digits=10, null=True)),
                ('cpc', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per click', max_digits=10, null=True)),
                ('ctr', models.DecimalField(blank=True, decimal_places=2, help_text='Click-through rate %', max_digits=5, null=True)),
                ('conversions', models.IntegerField(default=0)),
                ('cost_per_conversion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('metrics_data', models.JSONField(blank=True, default=dict, help_text='Additional metrics')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='meta_ads.metaadaccount')),
                ('ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='meta_ads.metaad')),
                ('ad_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='meta_ads.metaadset')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='meta_ads.metacampaign')),
            ],
            options={
                'verbose_name': 'Meta Insight',
                'verbose_name_plural': 'Meta Insights',
                'db_table': 'meta_insights',
                'ordering': ['-date_start'],
                'unique_together': {('account', 'date_start', 'date_stop'), ('ad', 'date_start', 'date_stop'), ('ad_set', 'date_start', 'date_stop'), ('campaign', 'date_start', 'date_stop')},
            },
        ),
    ]
