# Generated by Django 5.2.7 on 2025-10-07 21:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('industry', models.CharField(choices=[('technology', 'Technology'), ('healthcare', 'Healthcare'), ('finance', 'Finance'), ('education', 'Education'), ('retail', 'Retail'), ('manufacturing', 'Manufacturing'), ('consulting', 'Consulting'), ('real_estate', 'Real Estate'), ('food_beverage', 'Food & Beverage'), ('travel_tourism', 'Travel & Tourism'), ('automotive', 'Automotive'), ('fashion', 'Fashion'), ('sports_fitness', 'Sports & Fitness'), ('entertainment', 'Entertainment'), ('non_profit', 'Non-Profit'), ('other', 'Other')], max_length=50)),
                ('company_size', models.CharField(choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-500', '201-500 employees'), ('501-1000', '501-1000 employees'), ('1000+', '1000+ employees')], max_length=20)),
                ('website', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('business_description', models.TextField(help_text='Describe what your company does')),
                ('target_audience', models.TextField(help_text='Describe your target audience')),
                ('unique_selling_points', models.TextField(help_text='What makes your company unique?')),
                ('social_media_goals', models.TextField(help_text='What do you want to achieve with social media?')),
                ('preferred_tone', models.CharField(choices=[('professional', 'Professional'), ('casual', 'Casual'), ('friendly', 'Friendly'), ('authoritative', 'Authoritative'), ('humorous', 'Humorous'), ('inspirational', 'Inspirational')], default='professional', max_length=50)),
                ('content_topics', models.JSONField(default=list, help_text='List of topics to focus on')),
                ('keywords', models.JSONField(default=list, help_text='Important keywords for your business')),
                ('avoid_topics', models.JSONField(default=list, help_text='Topics to avoid')),
                ('primary_language', models.CharField(default='az', help_text='Primary language for content', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profiles',
                'db_table': 'company_profiles',
            },
        ),
    ]
