# Generated by Django 5.2.7 on 2025-12-03 08:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_posts_to_generate'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='branding_enabled',
            field=models.BooleanField(default=True, help_text='Automatically apply logo and slogan to images'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='branding_mode',
            field=models.CharField(choices=[('standard', 'Standard'), ('custom', 'Custom')], default='standard', help_text='Branding layout mode: Standard (fixed) or Custom (configurable)', max_length=10),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='logo_position',
            field=models.CharField(choices=[('bottom-left', 'Bottom Left'), ('bottom-right', 'Bottom Right'), ('top-left', 'Top Left'), ('top-right', 'Top Right'), ('middle-top', 'Middle Top'), ('middle', 'Center')], default='bottom-right', help_text='Logo position on images', max_length=20),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='logo_size_percent',
            field=models.IntegerField(default=5, help_text='Logo size as percentage of image width (2-25% for custom mode)', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='slogan',
            field=models.CharField(blank=True, help_text='Company slogan to overlay on images', max_length=200),
        ),
    ]
