# Generated by Django 5.2.3 on 2025-12-07 17:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_companyprofile_branding_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='slogan_position',
            field=models.CharField(choices=[('top-center', 'Top Center'), ('bottom-center', 'Bottom Center')], default='bottom-center', help_text='Slogan position on images', max_length=20),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='logo_position',
            field=models.CharField(choices=[('top-center', 'Top Center'), ('bottom-center', 'Bottom Center'), ('bottom-left', 'Bottom Left'), ('bottom-right', 'Bottom Right'), ('top-left', 'Top Left'), ('top-right', 'Top Right'), ('middle-top', 'Middle Top'), ('middle', 'Center')], default='top-center', help_text='Logo position on images', max_length=20),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='logo_size_percent',
            field=models.IntegerField(default=13, help_text='Logo size as percentage of image width (2-25% for custom mode)', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(25)]),
        ),
    ]
