# Generated by Django 5.2.3 on 2025-12-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_update_branding_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='meta_asset_id',
            field=models.CharField(blank=True, help_text='Meta Asset ID (Page ID) for Facebook/Instagram integration', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='meta_business_id',
            field=models.CharField(blank=True, help_text='Meta Business ID for Facebook/Instagram integration', max_length=100, null=True),
        ),
    ]
