# Generated by Django 5.2.3 on 2026-01-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_meta_business_suite_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='meta_asset_id',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='meta_business_id',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='ai_slogan',
            field=models.CharField(blank=True, help_text='AI slogan for Nano Banana prompt generation (in Azerbaijani)', max_length=200),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='slogan_enabled',
            field=models.BooleanField(default=True, help_text='Show slogan on posts (on/off toggle)'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='slogan',
            field=models.CharField(blank=True, help_text='Company slogan to overlay on images (for branding)', max_length=200),
        ),
    ]
