# Generated by Django 5.2.3 on 2026-01-26 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_add_ai_slogan_and_slogan_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='ai_slogan',
        ),
    ]
