# Generated by Django 5.2.3 on 2025-12-25 10:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_url', models.URLField(db_index=True, help_text='Original profile URL', max_length=500)),
                ('profile_username', models.CharField(blank=True, db_index=True, max_length=200)),
                ('platform', models.CharField(blank=True, help_text='instagram, facebook, linkedin, etc.', max_length=50)),
                ('preview_data', models.JSONField(help_text='OG preview and scraped profile data')),
                ('smm_analysis', models.JSONField(help_text='AI-generated SMM analysis')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed', models.DateTimeField(auto_now=True, help_text='Last time this cache was accessed')),
                ('access_count', models.IntegerField(default=1, help_text='Number of times this cache was accessed')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile Analysis',
                'verbose_name_plural': 'Profile Analyses',
                'db_table': 'profile_analyses',
                'ordering': ['-last_accessed'],
                'indexes': [models.Index(fields=['profile_url'], name='profile_ana_profile_6b492d_idx'), models.Index(fields=['profile_username', 'platform'], name='profile_ana_profile_f9a298_idx'), models.Index(fields=['-last_accessed'], name='profile_ana_last_ac_ddc0fa_idx')],
                'unique_together': {('profile_url',)},
            },
        ),
    ]
